server:
  port: 9897
spring:
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
        - id: members-service
          uri: lb://members-service
          predicates:
            - Path=/home/**
          filters:
            - AuthenticationFilter
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/emp/**
          filters:
            - AuthenticationFilter
        - id: leaves-service
          uri: lb://leaves-service
          predicates:
            - Path=/api/leave/**
          filters:
            - AuthenticationFilter
        - id: rm-service
          uri: lb://rm-service
          predicates:
            - Path=/api/rm/**
          filters:
            - AuthenticationFilter


  application:
    name: AUTH-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/